# Gradle Properties

# Java Home Configuration
# Убедитесь, что путь указан БЕЗ \bin в конце
# Для Windows используйте обратные слеши или forward slashes
org.gradle.java.home=C:/Program Files/jdk-17.0.0.1

# Gradle Daemon Configuration
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Java options
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
